# Chapter 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
n_rows = 100
n_columns = 100

df = pd.DataFrame(np.random.randint(0,100, size=(n_rows, n_columns)),
                  columns=['this is column %d' % i for i in range(n_columns)])

In [3]:
df

,this is column 0,this is column 1,this is column 2,this is column 3,this is column 4,this is column 5,this is column 6,this is column 7,this is column 8,this is column 9,...,this is column 90,this is column 91,this is column 92,this is column 93,this is column 94,this is column 95,this is column 96,this is column 97,this is column 98,this is column 99
0,99,48,87,45,83,6,94,86,70,12,...,30,2,53,20,94,65,44,22,94,16
1,46,21,17,48,30,30,24,9,86,68,...,89,7,86,41,30,83,27,46,97,24
2,47,34,26,79,99,24,82,29,74,0,...,22,98,48,24,72,56,36,2,55,25
3,14,42,76,9,32,68,26,10,94,36,...,46,8,53,77,4,77,90,59,81,39
4,75,95,81,39,2,70,50,52,91,79,...,96,68,27,90,95,9,37,27,52,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,58,87,29,45,57,94,12,60,36,25,...,19,42,3,69,31,15,87,2,65,68
96,88,6,62,66,3,39,34,95,57,75,...,30,92,11,24,23,3,38,79,88,24
97,45,16,10,88,19,26,2,65,53,66,...,3,58,57,35,80,19,77,11,58,50
98,68,60,43,55,87,30,21,5,12,34,...,41,80,90,90,61,61,77,56,55,53
99,19,60,3,22,37,37,96,88,87,26,...,47,26,52,16,48,71,36,84,6,41

# Chapter 2

This is the second chapter